version: '3'

services:
   api:
     build: .
     ports:
       - "5000:5000"

     volumes:
       - "./src:/src"
     tty: true
     environment:
       TZ: Asia/Tokyo
       FLASK_APP: run.py
       FLASK_ENV: developmentsxaz
     command: flask run -h 0.0.0.0
   db:
     image: mysql:5.7
     volumes:
       - ./mysql/mysql_data:/var/lib/mysql
       - ./mysql/sqls:/docker-entrypoint-initdb.d
     restart: always
     env_file: .env
     command: --innodb-use-native-aio=0

volumes:
    db_data:
